default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development_blog

test:
  <<: *default
  database: test_blog

production:
  <<: *default
  database: production_blog
